In [1]:
import pandas as pd
import numpy as np

In [2]:
df_original = pd.read_csv('olist.csv')

In [3]:
df_original

,original_index,review_text,review_text_processed,review_text_tokenized,polarity,rating,kfold_polarity,kfold_rating
0,97262,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,"['perfeito', 'chegou', 'antes', 'do', 'prazo']",1.0,5,1,1
1,72931,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,"['foi', 'uma', 'otima', 'compra', 'chegou', 'a...",1.0,5,1,1
2,19659,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,"['recebi', 'muito', 'rapido', 'um', 'otimo', '...",1.0,5,1,1
3,43054,Recomendo,recomendo,['recomendo'],1.0,5,1,1
4,59202,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,"['so', 'veio', 'uma', 'capa', 'comprei', 'ai',...",0.0,1,1,1
...,...,...,...,...,...,...,...,...
41739,49725,SUCESSO :D,sucesso :d,['sucesso'],1.0,5,10,10
41740,76794,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,"['tudo', 'ok', 'produto', 'entregue', 'no', 'p...",1.0,5,10,10
41741,72847,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,"['ultimamente', 'estao', 'atrasando', 'muito',...",0.0,1,10,10
41742,50905,recomendo,recomendo,['recomendo'],1.0,5,10,10
41743,6468,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,"['mascara', 'veio', 'com', 'um', 'pequeno', 'd...",0.0,2,10,10

In [4]:
# Acessando a primeir linha da coluna review_text
df_original.iloc[1]['review_text']

'Foi uma ótima compra! Chegou antes mesmo do prazo e o produto é igual o que estava no anúncio. Correspondeu as expectativas!'

In [11]:
# Filtrar o DataFrame para colunas selecionadas
df = df_original[['review_text', 'review_text_processed', 'polarity']]
df

,review_text,review_text_processed,polarity
0,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,1.0
1,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,1.0
2,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,1.0
3,Recomendo,recomendo,1.0
4,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,0.0
...,...,...,...
41739,SUCESSO :D,sucesso :d,1.0
41740,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,1.0
41741,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,0.0
41742,recomendo,recomendo,1.0
41743,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,0.0

In [6]:
#### Normalizar capitalização
exemplo = 'EXCELENTE!! Valeu demais passar um tempo pesquisando preços, pois encontrei esse ótimo carregador de celular, nota 10.'
print ("Antes de normalizar: ")
print(exemplo)
exemplo = exemplo.lower()
print ("Depois de de normalizar: \n")
print(exemplo)

Antes de normalizar:
EXCELENTE!! Valeu demais passar um tempo pesquisando preços, pois encontrei esse ótimo carregador de celular, nota 10.
Depois de de normalizar:

excelente!! valeu demais passar um tempo pesquisando preços, pois encontrei esse ótimo carregador de celular, nota 10.

#### Normalizando a coluna review_text inteira

In [17]:
# df['review_preproc'] = df['review_text'].apply(lambda x: x.lower())
df.loc[:, 'review_preproc'] = df['review_text'].apply(lambda x: x.lower())
df

,review_text,review_text_processed,polarity,review_preproc
0,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,1.0,perfeito....chegou antes do prazo.....
1,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,1.0,foi uma ótima compra! chegou antes mesmo do pr...
2,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,1.0,recebi muito rapido e um otimo custo beneficio
3,Recomendo,recomendo,1.0,recomendo
4,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,0.0,só veio uma capa comprei 3 aí paguei. mais de ...
...,...,...,...,...
41739,SUCESSO :D,sucesso :d,1.0,sucesso :d
41740,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,1.0,tudo ok. produto entregue no prazo correto.
41741,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,0.0,ultimamente estão atrasando muito as entregas
41742,recomendo,recomendo,1.0,recomendo
41743,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,0.0,a mascara veio com um pequeno defeito na estam...

#### Retirar pontuação

In [7]:
# Opção 1
exemplo_sem_punct_opcao1 = "".join(u for u in exemplo if u not in ("?", ".", ";", ":", "!", ","))
print(exemplo_sem_punct_opcao1)

'excelente valeu demais passar um tempo pesquisando preços pois encontrei esse ótimo carregador de celular nota 10'

In [9]:
# Opcão 2
from nltk.tokenize import RegexpTokenizer

# com '\w+' selecionamos apenas tokens de palavras ou dígitos
tokenizer = RegexpTokenizer(r'\w+')

exemplo_sem_punct_opcao2 = ' '.join(tokenizer.tokenize(exemplo))
print(exemplo_sem_punct_opcao2)

excelente valeu demais passar um tempo pesquisando preços pois encontrei esse ótimo carregador de celular nota 10

#### Retirando a pontuação da coluna inteira

In [21]:
# df['review_preproc'] = df['review_preproc'].apply(lambda x: ' '.join(tokenizer.tokenize(x))) # opção do colab
df.loc[:, 'review_preproc'] = df['review_preproc'].apply(lambda x: ' '.join(tokenizer.tokenize(x))) # opção alternativa, garante que df nãoé um subconjunto e evita warning
print(df)

                                             review_text  \
0                 Perfeito....chegou antes do prazo.....
1      Foi uma ótima compra! Chegou antes mesmo do pr...
2         Recebi muito rapido e um otimo custo beneficio
3                                              Recomendo
4      Só veio uma capa comprei 3 aí paguei. Mais de ...
...                                                  ...
41739                                         SUCESSO :D
41740       Tudo OK. Produto entregue no prazo correto.
41741      Ultimamente estão atrasando muito as entregas
41742                                          recomendo
41743  A mascara veio com um pequeno defeito na estam...

                                   review_text_processed  polarity  \
0                 perfeito....chegou antes do prazo.....       1.0
1      foi uma otima compra! chegou antes mesmo do pr...       1.0
2         recebi muito rapido e um otimo custo beneficio       1.0
3                                              recomendo       1.0
4      so veio uma capa comprei 3 ai paguei. mais de ...       0.0
...                                                  ...       ...
41739                                         sucesso :d       1.0
41740       tudo ok. produto entregue no prazo correto.        1.0
41741      ultimamente estao atrasando muito as entregas       0.0
41742                                          recomendo       1.0
41743  a mascara veio com um pequeno defeito na estam...       0.0

                                          review_preproc
0                         perfeito chegou antes do prazo
1      foi uma ótima compra chegou antes mesmo do pra...
2         recebi muito rapido e um otimo custo beneficio
3                                              recomendo
4      só veio uma capa comprei 3 aí paguei mais de 1...
...                                                  ...
41739                                          sucesso d
41740          tudo ok produto entregue no prazo correto
41741      ultimamente estão atrasando muito as entregas
41742                                          recomendo
41743  a mascara veio com um pequeno defeito na estam...

[41744 rows x 4 columns]

#### Retirar acentos

In [22]:
# Opção 1
repl = str.maketrans(
    "áéúíó",
    "aeuio"
)
palavra = 'ótimo'
palavra.translate(repl)

'otimo'

In [37]:
# Opção 2: Usar lib unidecode, https://github.com/avian2/unidecode.
try:
    import unidecode
    import logging
    libraries_installed = True
except ImportError:
    libraries_installed = False

if not libraries_installed:
    !pip install unidecode

try:
    import unidecode
    print(f"✅ Biblioteca está instalada e foi importada com sucesso!\n")
except ImportError as e:
    print(f"❌ Erro ao instalar a biblioteca: {e}\n")

exemplo_sem_acento = ' '.join([unidecode.unidecode(termo) for termo in exemplo_sem_punct_opcao2.split()])
exemplo_sem_acento

✅ Biblioteca está instalada e foi importada com sucesso!

'excelente valeu demais passar um tempo pesquisando precos pois encontrei esse otimo carregador de celular nota 10'

#### Retirando os acentos da coluna inteira

In [43]:
df.loc[:, 'review_preproc'] = df['review_preproc'].apply(lambda x: ' '.join([unidecode.unidecode(termo) for termo in x.split()]))
df

,review_text,review_text_processed,polarity,review_preproc
0,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,1.0,perfeito chegou antes do prazo
1,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,1.0,foi uma otima compra chegou antes mesmo do pra...
2,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,1.0,recebi muito rapido e um otimo custo beneficio
3,Recomendo,recomendo,1.0,recomendo
4,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,0.0,so veio uma capa comprei 3 ai paguei mais de 1...
...,...,...,...,...
41739,SUCESSO :D,sucesso :d,1.0,sucesso d
41740,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,1.0,tudo ok produto entregue no prazo correto
41741,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,0.0,ultimamente estao atrasando muito as entregas
41742,recomendo,recomendo,1.0,recomendo
41743,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,0.0,a mascara veio com um pequeno defeito na estam...

#### Retirar stopwords

In [44]:
# Opção 1: criar uma lista manual
stopwords = ['de', 'para', 'uma', 'o', 'e'] # aqui listamos as palavras que mais se repetem, de acordo com o domínio de aplicação

In [54]:
# Opção 2: usar uma lista de stopwords compilada pela biblioteca NLTK
import nltk
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('portuguese')
# stopwords

print(f"Com stopwords: {exemplo_sem_acento}\n")
exemplo_sem_stopwords = ' '.join([termo for termo in exemplo_sem_acento.split() if termo not in stopwords])
print(f"Sem stopwords: {exemplo_sem_stopwords}")

Com stopwords: excelente valeu demais passar um tempo pesquisando precos pois encontrei esse otimo carregador de celular nota 10

Sem stopwords: excelente valeu demais passar tempo pesquisando precos pois encontrei otimo carregador celular nota 10

[nltk_data] Downloading package stopwords to C:\Users\Pc
[nltk_data]     Gamer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

#### Remover stopwords da coluna review_preproc por inteiro

In [56]:
df.loc[:, 'review_preproc'] = df['review_preproc'].apply(lambda x: ' '.join([termo for termo in x.split() if termo not in stopwords]))
df

,review_text,review_text_processed,polarity,review_preproc
0,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,1.0,perfeito chegou antes prazo
1,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,1.0,otima compra chegou antes prazo produto igual ...
2,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,1.0,recebi rapido otimo custo beneficio
3,Recomendo,recomendo,1.0,recomendo
4,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,0.0,so veio capa comprei 3 ai paguei 100 reais capa
...,...,...,...,...
41739,SUCESSO :D,sucesso :d,1.0,sucesso d
41740,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,1.0,tudo ok produto entregue prazo correto
41741,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,0.0,ultimamente estao atrasando entregas
41742,recomendo,recomendo,1.0,recomendo
41743,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,0.0,mascara veio pequeno defeito estampa derretido...

#### Stemmização da coluna inteira

In [58]:
nltk.download('rslp')
stemmer = nltk.stem.RSLPStemmer()

[nltk_data] Downloading package rslp to C:\Users\Pc
[nltk_data]     Gamer\AppData\Roaming\nltk_data...
[nltk_data]   Package rslp is already up-to-date!

In [59]:
df.loc[:, 'review_preproc'] = df['review_preproc'].apply(lambda x: ' '.join(stemmer.stem(termo) for termo in x.split()))
df

,review_text,review_text_processed,polarity,review_preproc
0,Perfeito....chegou antes do prazo.....,perfeito....chegou antes do prazo.....,1.0,perfeit cheg ant praz
1,Foi uma ótima compra! Chegou antes mesmo do pr...,foi uma otima compra! chegou antes mesmo do pr...,1.0,otim compr cheg ant praz produt igual anunci c...
2,Recebi muito rapido e um otimo custo beneficio,recebi muito rapido e um otimo custo beneficio,1.0,receb rap otim cust benefici
3,Recomendo,recomendo,1.0,recom
4,Só veio uma capa comprei 3 aí paguei. Mais de ...,so veio uma capa comprei 3 ai paguei. mais de ...,0.0,so vei cap compr 3 ai pag 100 real cap
...,...,...,...,...
41739,SUCESSO :D,sucesso :d,1.0,sucess d
41740,Tudo OK. Produto entregue no prazo correto.,tudo ok. produto entregue no prazo correto.,1.0,tud ok produt entreg praz corret
41741,Ultimamente estão atrasando muito as entregas,ultimamente estao atrasando muito as entregas,0.0,ultim esta atras entreg
41742,recomendo,recomendo,1.0,recom
41743,A mascara veio com um pequeno defeito na estam...,a mascara veio com um pequeno defeito na estam...,0.0,masc vei pequen defeit estamp derret so nao de...